- name: "master/config.yml, populate oo_hosts_to_config host group if needed"
  hosts: localhost
  gather_facts: no
  tasks:
  - name: "Evaluate oo_host_group_exp if it's set"
    add_host: "name={{ item }} groups=oo_hosts_to_config"
    with_items: "{{ oo_host_group_exp | default('') }}"
    when: oo_host_group_exp is defined

- name: "Gather facts for nodes in {{ oo_env }}"
  hosts: "tag_env-host-type-{{ oo_env }}-openshift-node"
  connection: ssh
  user: root

- name: "Retrieve public ip"
  hosts: oo_hosts_to_config
  connection: ssh
  user: root
  gather_facts: yes
  tasks:
    - command: 'curl "http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" -H "Metadata-Flavor: Google"'
      register: output
    - set_fact: gce_public_ip="{{ output.stdout }}"

- name: "Set Origin specific facts on localhost (for later use)"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Setting openshift_node_ips fact on localhost
      set_fact:
        openshift_node_ips: "{{ hostvars
            | oo_select_keys(groups['tag_env-host-type-' + oo_env + '-openshift-node'])
            | oo_collect(attribute='ansible_default_ipv4.address') }}"
      when: groups['tag_env-host-type-' + oo_env + '-openshift-node'] is defined

- name: "Configure instances"
  hosts: oo_hosts_to_config
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  roles:
    - repos
    - {
        role: openshift_master,
        openshift_node_ips: "{{ hostvars['localhost'].openshift_node_ips | default(['']) }}",
        openshift_public_ip: "{{ gce_public_ip }}",
        openshift_env: "{{ oo_env }}",
      }
    - pods
    - os_env_extras
