- name: master/config.yml, populate oo_hosts_to_config host group if needed
  hosts: localhost
  gather_facts: no
  tasks:
  - name: "Evaluate oo_host_group_exp if it's set"
    add_host: "name={{ item }} groups=oo_hosts_to_config"
    with_items: "{{ oo_host_group_exp | default('') }}"
    when: oo_host_group_exp is defined

- name: Gather facts for nodes in {{ oo_env }}
  hosts: "tag_env-host-type-{{ oo_env }}-openshift-node"

- name: "Configure instances"
  hosts: oo_hosts_to_config
  vars_files:
  - vars.yml
  roles:
    - repos
    - openshift_master
    - pods
    - os_env_extras
