---
- name: Set hostname
  hostname: name={{ openshift_hostname }}

- name: Update all packages
  yum: name=* state=latest

- name: Configure local facts file
  file: path=/etc/ansible/facts.d/ state=directory mode=0750

- name: Set common OpenShift facts
  include: set_facts.yml
  facts:
  - section: common
    option: env
    value: "{{ openshift_env | default('default') }}"
  - section: common
    option: host_type
    value: "{{ openshift_host_type }}"
  - section: common
    option: debug_level
    value: "{{ openshift_debug_level }}"
