---
- name: Gather master facts
  hosts: oo_first_master
  roles:
  - openshift_facts
  tasks:

- name: Configure node instances
  hosts: oo_nodes_to_config
  gather_facts: no
  vars:
    openshift_node_master_api_url: "{{ hostvars[openshift_first_master].openshift.master.api_url }}"
  roles:
  - openshift_node
  tasks:
  - name: Create group for deployment type
    group_by: key=oo_nodes_deployment_type_{{ openshift.common.deployment_type }}
    changed_when: False

# Additional config for online type deployments
- name: Additional instance config
  hosts: oo_nodes_deployment_type_online
  gather_facts: no
  roles:
  - os_env_extras
  - os_env_extras_node
