---
- name: Terminate instance(s)
  hosts: localhost

  vars_files:
    - vars.yml

  tasks:
    - debug: msg="Retrieve node names"
    - debug: msg="Retrieve master names"
    - debug: var=groups

- include: ../openshift-node/terminate.yml
  vars:
    oo_host_group_exp: 'groups["tag_env-host-type-{{ cluster_id }}-openshift-node"]'
    gce_service_account_email: "1043659492591-r0tpbf8q4fbb9dakhjfhj89e4m1ld83t@developer.gserviceaccount.com"
    gce_pem_file: "~/.gce/openshift-gce-devel_priv_key.pem"
    gce_project_id: "openshift-gce-devel"

- include: ../openshift-master/terminate.yml
  vars:
    oo_host_group_exp: 'groups["tag_env-host-type-{{ cluster_id }}-openshift-master"]'
    gce_service_account_email: "1043659492591-r0tpbf8q4fbb9dakhjfhj89e4m1ld83t@developer.gserviceaccount.com"
    gce_pem_file: "~/.gce/openshift-gce-devel_priv_key.pem"
    gce_project_id: "openshift-gce-devel"
